name: hungryyy
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.2
  rflutter_alert: ^1.0.3
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.8
  geolocator: ^5.3.2+2
  collection: ^1.0.0
  geocoder: ^0.2.1
  intl: ^0.16.1
  google_maps_flutter: 0.5.18
  location: ^3.0.0
  flutter_polyline_points: 0.2.0
  flutter_webview_plugin: ^0.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: GT Eesti
      fonts:
        - asset: fonts/GT-Eesti-Pro-Display-Regular.ttf

  assets:
    - images/
    - assets/map_style.txt



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
